{{- if .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "minio.fullname" . }}
  {{- if .Values.metrics.podMonitor.namespace }}
  namespace: {{ .Values.metrics.podMonitor.namespace }}
  {{- end }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.metrics.podMonitor.additionalLabels }}
{{ toYaml .Values.metrics.podMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    {{- if .Values.tls.enabled }}
    - port: https
    {{ else }}
    - port: http
    {{- end }}
      path: /minio/v2/metrics/cluster
      {{- if .Values.metrics.podMonitor.interval }}
      interval: {{ .Values.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if not .Values.metrics.podMonitor.public }}
      bearerTokenSecret:
        name: {{ template "minio.fullname" . }}-prometheus
        key: token
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      app: {{ include "minio.name" . }}
      release: {{ .Release.Name }}
{{- end }}
