name: Go

on:
  push:
    tags:
      - "RELEASE.*"

permissions:
  contents: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.7
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Build
        env:
          GO111MODULE: on
        run: |
          make crosscompile
      - name: Release
        run: |
          gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} -d
          echo 'Uploading files in bin/*:'
          ls  bin/*
          gh release upload ${{ github.ref_name }} bin/*
